version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
